### PR TITLE
[app] Expand interaction to allow slash command and other.

### PR DESCRIPTION
**Pull request by noaione**
## Summary

This PR add the ability to create slash command, user command, message command on either the bot directly or on cogs.

This PR is still work in progress. :)

Sample:

```py
from discord.ext import commands

bot = commands.Bot()

@bot.slash_command()
async def echo(ctx, message: str):
	await ctx.send(message)

bot.run("token")
```

Can also be used via cogs:

```py
from discord.ext import app, commands

class TestCog(commands.Cog):
	def __init__(self, bot):
		self.bot = bot

	@app.slash_command()
	async def echo(self, ctx, message: str):
		await ctx.send(message)

bot = commands.Bot()
bot.add_cog(TestCog(bot))

bot.run("token")
```

## Checklist

- [x] If code changes were made then they have been tested.
    - [x] I have updated the documentation to reflect the changes.
- [ ] This PR fixes an issue.
- [x] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [ ] This PR is **not** a code change (e.g. documentation, README, ...)

### CODE REVIEW

**Comment by noaione** [comment]
Difference between other repo (that I've seen atleast).

1. Use it's own folder for managing all applications.
2. Making sure it's being separated as much as possible from the original `ext.commands` implementation.
3. Allow using the same name as long as the `type` is different.
4. Most of the stuff are typed.

Most of the code as I'm writing this is ready, the only thing left is some implementation to Slash group.
I borrowed a lot of code from `pycord` first implementation and some part from `dislash.py` for the group implementation.

Most of the code written here are mostly the same as "*improvement*" that I'm making for [pycord](https://github.com/Pycord-Development/pycord/pull/184)

**Comment by noaione** [comment]
After some more testing, slash/user/message now works as intended.

**Comment by technicaldiff** [comment]
Hey! thanks for working on this.Is this going to be eventually merged with pycord?

**Comment by noaione** [comment]
No, it will be kept here since pycord already has their own implementation.
You can use the [`feature/slash`](https://github.com/Pycord-Development/pycord/tree/feature/slash) branch on pycord if you want support for application command.

**Comment by technicaldiff** [comment]
alright. Thanks!

**Pull request merged**
